### ISSUE TITLE
Add Remaining Social Links

### ISSUE THREAD

**Issue by hwkr** [hwkr/hwkr.github.io#1]
I'm missing some icons in Typicon so I'll need to bring them in from elsewhere.

Icons needed:

* Stack Echange
* Steam

Build the icon font maybe using [this loader](https://github.com/DragonsInn/fontgen-loader) then re-add these to `config.js`,

```
    {
      "href": "http://ux.stackexchange.com/users/77302/ben",
      "tooltip": "Exchange with me",
      "icon": "stack-exchange"
    },
    {
      "href": "http://steamcommunity.com/id/byteHero/",
      "tooltip": "Game with me",
      "icon": "social-steam"
    }
```

**Comment by dominiquecharlebois** [comment]
Use Fontello to create all the icons from everywhere !

**Comment by hwkr** [comment]
No :angry:
